import React from "react";

const boardgames = [
  {
    id: 1,
    name: "exploding kitten",
    category: "family",
    price: 15.99,
    img: "https://m.media-amazon.com/images/I/510RZPoe1BS._AC_SX679_.jpg",
    complexity: 1.08,
    player: "2-5",
    playingTime: "15",
    amount: 1,
    designer: "Matthew Inman, Elan Lee, Shane Small",
    desc: "Exploding Kittens is a kitty-powered version of Russian Roulette. Players take turns drawing cards until someone draws an exploding kitten and loses the game. The deck is made up of cards that let you avoid exploding by peeking at cards before you draw, forcing your opponent to draw multiple cards, or shuffling the deck. The game gets more and more intense with each card you draw because fewer cards left in the deck means a greater chance of drawing the kitten and exploding in a fiery ball of feline hyperbole.",
  },
  {
    id: 2,
    name: "splendor",
    category: "strategy",
    price: 35.99,
    img: "https://m.media-amazon.com/images/I/8127PSclV9S._AC_SX679_.jpg",
    complexity: 1.79,
    player: "2-4",
    playingTime: "30",
    amount: 1,
    designer: "Marc André",
    desc: "Splendor is a game of chip-collecting and card development. Players are merchants of the Renaissance trying to buy gem mines, means of transportation, shops—all in order to acquire the most prestige points. If you're wealthy enough, you might even receive a visit from a noble at some point, which of course will further increase your prestige.",
  },
  {
    id: 3,
    name: "ticket to ride",
    category: "strategy",
    price: 47.99,
    img: "https://m.media-amazon.com/images/I/91YNJM4oyhL._AC_SX679_.jpg",
    complexity: 1.84,
    player: "2-5",
    playingTime: "30-60",
    amount: 1,
    designer: "Alan R. Moon",
    desc: "With elegantly simple gameplay, Ticket to Ride can be learned in under 15 minutes. Players collect cards of various types of train cars they then use to claim railway routes in North America. The longer the routes, the more points they earn. Additional points come to those who fulfill Destination Tickets – goal cards that connect distant cities; and to the player who builds the longest continuous route.",
  },
  {
    id: 4,
    name: "dead of winter",
    category: "crossroads",
    price: 55.99,
    img: "https://m.media-amazon.com/images/I/81LWvhGlPZL._AC_SX679_.jpg",
    complexity: 3.01,
    player: "2-5",
    playingTime: "60-120",
    amount: 1,
    designer: "Jonathan Gilmour, Isaac Vega",
    desc: "Dead of Winter is a meta-cooperative psychological survival game. This means players are working together toward one common victory condition, but for each individual player to achieve victory, they must also complete their personal secret objective, which could relate to a psychological tick that is fairly harmless to most others in the colony, a dangerous obsession that could put the main objective at risk, a desire for sabotage of the main mission, or (worst of all) vengeance against the colony! Games could end with all players winning, some winning and some losing, or all players losing. Work toward the group's goal, but don't get walked all over by a loudmouth who's looking out only for their own interests!",
  },
  {
    id: 5,
    name: "bang!",
    category: "hidden roles",
    price: 19.99,
    img: "https://m.media-amazon.com/images/I/61ewj94O5yL._AC_SY879_.jpg",
    complexity: 1.63,
    player: "4-7",
    playingTime: "20-40",
    amount: 1,
    designer: "Emiliano Sciarra",
    desc: "The card game BANG! recreates an old-fashioned spaghetti western shoot-out, with each player randomly receiving a Character card to determine special abilities, and a secret Role card to determine their goal.",
  },
  {
    id: 6,
    name: "bears vs babies",
    category: "family",
    price: 24.99,
    img: "https://m.media-amazon.com/images/I/71ZSZz+YEQL._AC_SX679_.jpg",
    complexity: 1.29,
    player: "2-5",
    playingTime: "15-20",
    amount: 1,
    designer: "Matthew Inman, Elan Lee",
    desc: "Bears vs Babies is a card game in which you build handsome, incredible monsters who go to war with horrible, awful babies. The shared deck of cards consists of bear parts (and other monster parts) and baby cards. When you draw a part, you use it to build a monster for yourself; when you draw a baby, it goes in the center of the table. When babies are provoked, they attack, and anyone who has fewer monster parts than the number of attacking babies loses their monster; everyone with more parts than babies defeats this infantile army and scores.",
  },
];

export default boardgames